### ISSUE TITLE
他のプロセスがファイルを使用中のため、プロセスがアクセスできません。

### ISSUE THREAD

**Issue by kdrkdrkdr** [ikegami-yukino/asa-python#1]
asa, cabocha, mecab ともにまともに設置して, ジャバランタイムもよく設置したが, 続いて下記のようなエラーが発生します.. 解決方法はありますか？

------------------------------
他のプロセスがファイルを使用中のため、プロセスがアクセスできません。

Exception ignored in: <function ASA.__del__ at 0x02E4C390>
Traceback (most recent callast):

File "C:\Users\power\AppData\Local\Programs\Python\Python37-32\lib\site-packages\asa\asa.py", line62, in_del_____

Permission Error:[Win Error 32]他のプロセスがファイルを使用中のため、プロセスがアクセスできません: 'C:\Users\power\\AppData\\Local\\Temp\tmpmab4uro5'

**Comment by ikegami-yukino** [comment]
@kdrkdrkdr 
エラー報告ありがとうございます。
Windows 10での利用でしょうか？

Windowsは他のOSとファイルの扱いの挙動が違うようです。

たとえば、以下URLのような例があります。
https://qiita.com/yukinoi/items/1fe023408d3e684da983#%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%92%E3%81%AA%E3%81%8B%E3%81%AA%E3%81%8B%E9%9B%A2%E3%81%97%E3%81%A6%E3%81%8F%E3%82%8C%E3%81%AA%E3%81%84%E5%95%8F%E9%A1%8C

とりあえず上記記事の対策で解決できるか試してみます。

**Comment by ikegami-yukino** [comment]
@kdrkdrkdr 
こちらのリポジトリはオリジナルのASA (Java版) をPythonで呼び出すクライアントモジュールとなります。
ですが、最近オリジナルのASA (Java版) を作った竹内研究室でPython版のASAが公開されているようです。
もしよろしければ、わたしのこのクライアントモジュールではなく、竹内研究室で公開されているものをご利用するようお願い致します。

竹内研究室で公開されているPython版のASAは下記URLを参照してください。
https://github.com/Takeuchi-Lab-LM/python_asa

**Comment by kdrkdrkdr** [comment]
ご回答ありがとうございます。
Windows 10 を使用しています。
